repos:
  - repo: local
    hooks:
      - id: block-ipynb-in-protected-dirs
        name: Protect examples and howtos
        files: ^(examples|howtos)/.*\.ipynb$
        entry: |
          python -c "import sys;
          if len(sys.argv) > 1:
              print('\n❌ ERROR: MANUAL IPYNB MODIFICATION DETECTED\n');
              sys.exit(1)"
        language: system
        pass_filenames: true